# Agent Configuration for Panini-Filesystem
[agent]
name = "filesystem-agent"
type = "core-component"
priority = "high"
dependencies = ["semantic-core", "publications"]

[coordination]
master_hub = "https://github.com/stephanedenis/Panini-Ecosystem"
sync_interval = 300  # 5 minutes
health_check = true

[missions]
# Missions spécialisées pour ce repo
build_and_test = true
semantic_validation = true
filesystem_monitoring = true

[communication]
# Protocoles de communication inter-agents
mqtt_broker = "mqtt://coordination.panini.local"
webhook_endpoint = "/api/coordination/filesystem"
status_broadcast = true

[local_copilotage]
# Copilotage optimisé pour filesystem
autonomous_compilation = true
semantic_analysis = true
performance_monitoring = true
publication_sync = false  # Délégué à Panini-Publications
