# Configuration GitHub Pages pour PaniniFS
# Dashboard de gouvernance autonome

title: "PaniniFS - Gouvernance Autonome"
description: "Dashboard de monitoring et gouvernance autonome pour écosystème intelligent"
baseurl: ""
url: "https://paninifs.com"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
navbar:
  - title: "Dashboard"
    url: "/dashboard.html"
  - title: "GitHub"
    url: "https://github.com/stephanedenis/PaniniFS"

# Theme (optionnel)
theme: minima

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
